#include "errors.h"
/*
 * Function called to raise an errors generated by
 * the compiler
 */
void raise_error(ERRORS error) {
	printf("Error number %i: %s on line %i \n", error, errors[error], current_line);
}
